.PHONY: help install dev fmt lint typecheck test cov run worker outbox migrate revision seed up down logs ps shell-api shell-db build clean

PYTHON ?= python
COMPOSE ?= docker compose

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

install: ## Install runtime + dev dependencies
	$(PYTHON) -m pip install -U pip
	$(PYTHON) -m pip install -e ".[dev]"

dev: ## Start API locally with reload (requires Postgres + Redis running)
	uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

worker: ## Start the classification worker locally
	arq app.workers.classification_worker.WorkerSettings

outbox: ## Start the outbox publisher locally
	$(PYTHON) -m app.workers.outbox_publisher

fmt: ## Auto-format
	ruff format app tests scripts

lint: ## Static checks
	ruff check app tests scripts

typecheck: ## mypy
	mypy app

test: ## Run tests
	pytest -q

cov: ## Tests with coverage
	pytest --cov=app --cov-report=term-missing --cov-report=xml

migrate: ## Apply DB migrations
	alembic upgrade head

revision: ## Create an autogenerated revision: make revision m="message"
	alembic revision --autogenerate -m "$(m)"

seed: ## Seed demo drugs and synonyms
	$(PYTHON) -m scripts.seed_drugs
	$(PYTHON) -m scripts.seed_synonyms

build: ## Build Docker image
	$(COMPOSE) build

up: ## Bring up the full stack
	$(COMPOSE) up -d

down: ## Tear down the stack
	$(COMPOSE) down

logs: ## Follow logs (svc=worker for a single service)
	$(COMPOSE) logs -f $(svc)

ps: ## List running services
	$(COMPOSE) ps

shell-api: ## Shell into the api container
	$(COMPOSE) exec api /bin/bash

shell-db: ## psql into the local database
	$(COMPOSE) exec postgres psql -U postgres -d drug_safety

clean: ## Remove caches and build artifacts
	rm -rf .pytest_cache .mypy_cache .ruff_cache .coverage htmlcov dist build *.egg-info
	find . -type d -name __pycache__ -exec rm -rf {} +
